require 'ap'
require 'uri'
require 'yaml'
require 'fileutils'
require 'aws-sdk'

require 'xeroxer/xeroxer'
require 'xeroxer/resource'
require 'xeroxer/file'
require 'xeroxer/S3'
require 'xeroxer/http'
require 'xeroxer/exceptions'